import {
  createCipheriv,
  createDecipheriv,
  createHash,
  hkdfSync,
  randomBytes,
  timingSafeEqual
} from 'crypto'

/**
 * Node port of the phone's VaultCrypto (shared/…/sync/VaultCrypto.kt).
 * Byte-exactness is pinned by desktop/test/vault-crypto.test.ts, whose
 * vectors were generated by the Kotlin implementation itself
 * (shared/…/CrossPlatformVectorTest.kt). Field shapes match the Kotlin
 * data classes: nonce and ciphertext travel as separate base64url strings.
 */

const RECOVERY_PREFIX = 'WV1'
const ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'
const SALT = 'WoVoice recovery v1'

export interface WrappedVaultKey {
  wrappedKey: string
  nonce: string
  keyVersion: number
}

export interface EncryptedRecord {
  nonce: string
  ciphertext: string
}

export function newSecret(): Buffer {
  return randomBytes(32)
}

function base32Encode(bytes: Buffer): string {
  let output = ''
  let buffer = 0
  let bits = 0
  for (const byte of bytes) {
    buffer = (buffer << 8) | byte
    bits += 8
    while (bits >= 5) {
      bits -= 5
      output += ALPHABET[(buffer >>> bits) & 31]
    }
  }
  if (bits > 0) output += ALPHABET[(buffer << (5 - bits)) & 31]
  return output
}

function base32Decode(value: string): Buffer {
  let buffer = 0
  let bits = 0
  const bytes: number[] = []
  for (const character of value) {
    const index = ALPHABET.indexOf(character)
    if (index < 0) throw new Error(`Invalid base32 character: ${character}`)
    buffer = (buffer << 5) | index
    bits += 5
    if (bits >= 8) {
      bits -= 8
      bytes.push((buffer >>> bits) & 0xff)
    }
  }
  return Buffer.from(bytes)
}

export function encodeRecoveryKey(secret: Buffer): string {
  if (secret.length !== 32) throw new Error('Recovery secret must be 32 bytes')
  const payload = base32Encode(secret)
  const checksum = base32Encode(createHash('sha256').update(secret).digest()).slice(0, 6)
  const groups = (payload + checksum).match(/.{1,4}/g) ?? []
  return [RECOVERY_PREFIX, ...groups].join('-')
}

export function decodeRecoveryKey(value: string): Buffer | null {
  try {
    const normalized = value
      .toUpperCase()
      .replace(/[^A-Z0-9]/g, '')
      .replace(/O/g, '0')
      .replace(/I/g, '1')
      .replace(/L/g, '1')
    if (!normalized.startsWith(RECOVERY_PREFIX)) return null
    const encoded = normalized.slice(RECOVERY_PREFIX.length)
    if (encoded.length !== 58) return null
    const secret = base32Decode(encoded.slice(0, 52))
    if (secret.length !== 32) return null
    const expected = base32Encode(createHash('sha256').update(secret).digest()).slice(0, 6)
    const actual = Buffer.from(encoded.slice(-6))
    const expectedBuffer = Buffer.from(expected)
    if (actual.length !== expectedBuffer.length || !timingSafeEqual(actual, expectedBuffer)) return null
    return secret
  } catch {
    return null
  }
}

function hkdfSha256(inputKey: Buffer, info: Buffer, outputLength: number): Buffer {
  return Buffer.from(hkdfSync('sha256', inputKey, Buffer.from(SALT), info, outputLength))
}

function metadata(
  accountId: string,
  type: string,
  id: string,
  keyVersion: number,
  schemaVersion: number
): Buffer {
  return Buffer.from(`${accountId}|${type}|${id}|${keyVersion}|${schemaVersion}`, 'utf-8')
}

function encrypt(key: Buffer, plaintext: Buffer, aad: Buffer): EncryptedRecord {
  const nonce = randomBytes(12)
  const cipher = createCipheriv('aes-256-gcm', key, nonce)
  cipher.setAAD(aad)
  const ciphertext = Buffer.concat([cipher.update(plaintext), cipher.final(), cipher.getAuthTag()])
  return { nonce: nonce.toString('base64url'), ciphertext: ciphertext.toString('base64url') }
}

function decrypt(key: Buffer, record: EncryptedRecord, aad: Buffer): Buffer {
  const decipher = createDecipheriv('aes-256-gcm', key, Buffer.from(record.nonce, 'base64url'))
  decipher.setAAD(aad)
  const full = Buffer.from(record.ciphertext, 'base64url')
  const tag = full.subarray(full.length - 16)
  const ciphertext = full.subarray(0, full.length - 16)
  decipher.setAuthTag(tag)
  return Buffer.concat([decipher.update(ciphertext), decipher.final()])
}

export function wrapVaultKey(
  vaultKey: Buffer,
  recoverySecret: Buffer,
  accountId: string,
  keyVersion: number
): WrappedVaultKey {
  if (vaultKey.length !== 32 || recoverySecret.length !== 32 || keyVersion <= 0) {
    throw new Error('Invalid vault wrap inputs')
  }
  const wrappingKey = hkdfSha256(recoverySecret, Buffer.from(accountId), 32)
  const wrapped = encrypt(wrappingKey, vaultKey, Buffer.from(`vault|${accountId}|${keyVersion}`))
  return { wrappedKey: wrapped.ciphertext, nonce: wrapped.nonce, keyVersion }
}

export function unwrapVaultKey(
  wrapped: WrappedVaultKey,
  recoverySecret: Buffer,
  accountId: string
): Buffer | null {
  try {
    const wrappingKey = hkdfSha256(recoverySecret, Buffer.from(accountId), 32)
    const vaultKey = decrypt(
      wrappingKey,
      { nonce: wrapped.nonce, ciphertext: wrapped.wrappedKey },
      Buffer.from(`vault|${accountId}|${wrapped.keyVersion}`)
    )
    return vaultKey.length === 32 ? vaultKey : null
  } catch {
    return null
  }
}

export function encryptRecord(
  vaultKey: Buffer,
  plaintext: Buffer,
  accountId: string,
  type: string,
  recordId: string,
  keyVersion: number,
  schemaVersion: number
): EncryptedRecord {
  return encrypt(vaultKey, plaintext, metadata(accountId, type, recordId, keyVersion, schemaVersion))
}

export function decryptRecord(
  vaultKey: Buffer,
  record: EncryptedRecord,
  accountId: string,
  type: string,
  recordId: string,
  keyVersion: number,
  schemaVersion: number
): Buffer | null {
  try {
    return decrypt(vaultKey, record, metadata(accountId, type, recordId, keyVersion, schemaVersion))
  } catch {
    return null
  }
}
