import { strict as assert } from 'node:assert'
import { createCipheriv } from 'crypto'
import { test, describe } from 'node:test'
import {
  decodeRecoveryKey,
  decryptRecord,
  encodeRecoveryKey,
  encryptRecord,
  newSecret,
  unwrapVaultKey,
  wrapVaultKey
} from '../src/main/vault-crypto'

/**
 * The HKDF, recovery-key, and AES-GCM vectors below were generated by the
 * authoritative Kotlin implementation (shared/…/CrossPlatformVectorTest.kt).
 * If these pass, the Node port is byte-exact with the phone.
 */

const SECRET = Buffer.from(Array.from({ length: 32 }, (_, i) => i))

describe('vault crypto (byte-exact with Kotlin)', () => {
  test('HKDF matches the Kotlin implementation', () => {
    // Mirrors CrossPlatformVectorTest: hkdfSha256(secret, salt="WoVoice recovery v1", info="acct-123", 32)
    const { hkdfSync } = require('crypto') as typeof import('crypto')
    const out = Buffer.from(
      hkdfSync('sha256', SECRET, Buffer.from('WoVoice recovery v1'), Buffer.from('acct-123'), 32)
    )
    assert.equal(out.toString('hex'), '47051702b02052ffc5f60a0bbc8fbe43e5cca05a18e0d87a96600d52d25dce82')
  })

  test('recovery key encoding matches the Kotlin implementation', () => {
    assert.equal(
      encodeRecoveryKey(SECRET),
      'WV1-000G-40R4-0M30-E209-185G-R38E-1W81-24GK-2GAH-C5RR-34D1-P70X-3RFG-CC6W-TA'
    )
  })

  test('recovery key decode round-trips and validates the checksum', () => {
    const key = encodeRecoveryKey(SECRET)
    assert.deepEqual(decodeRecoveryKey(key), SECRET)
    assert.equal(decodeRecoveryKey(key.replace('000G', '000H')), null)
    assert.equal(decodeRecoveryKey('WV1-short'), null)
    assert.equal(decodeRecoveryKey('nonsense'), null)
    // Phone-style confusable normalization: O→0, I/L→1
    const withConfusables = encodeRecoveryKey(SECRET).replace('000G', 'OOOG')
    assert.deepEqual(decodeRecoveryKey(withConfusables), SECRET)
  })

  test('AES-256-GCM ciphertext matches the Kotlin implementation', () => {
    // Mirrors CrossPlatformVectorTest: fixed key/nonce/AAD/plaintext.
    const vaultKey = Buffer.from(Array.from({ length: 32 }, (_, i) => i + 0x40))
    const nonce = Buffer.from(Array.from({ length: 12 }, (_, i) => i))
    const aad = 'acct-123|history|rec-1|1|1'
    const cipher = createCipheriv('aes-256-gcm', vaultKey, nonce)
    cipher.setAAD(Buffer.from(aad))
    const ciphertext = Buffer.concat([
      cipher.update(Buffer.from('Hello cross-platform')),
      cipher.final(),
      cipher.getAuthTag()
    ])
    assert.equal(
      ciphertext.toString('hex'),
      '7260001418ac27d2ad61f3efc881adcfe5ab5f646a7dc4eb784fc22b1335f7013cd20d48'
    )
  })

  test('record encrypt/decrypt round-trips and AAD binds the identity', () => {
    const vaultKey = newSecret()
    const plaintext = Buffer.from('{"text":"Hello WoVoice"}')
    const sealed = encryptRecord(vaultKey, plaintext, 'acct-1', 'history', 'rec-9', 1, 1)
    assert.deepEqual(
      decryptRecord(vaultKey, sealed, 'acct-1', 'history', 'rec-9', 1, 1),
      plaintext
    )
    // Any metadata change must break decryption (no record shuffling across ids).
    assert.equal(decryptRecord(vaultKey, sealed, 'acct-2', 'history', 'rec-9', 1, 1), null)
    assert.equal(decryptRecord(vaultKey, sealed, 'acct-1', 'dictionary', 'rec-9', 1, 1), null)
    assert.equal(decryptRecord(vaultKey, sealed, 'acct-1', 'history', 'rec-8', 1, 1), null)
  })

  test('vault wrap/unwrap round-trips with the recovery secret', () => {
    const vaultKey = newSecret()
    const recoverySecret = newSecret()
    const wrapped = wrapVaultKey(vaultKey, recoverySecret, 'acct-7', 1)
    assert.deepEqual(unwrapVaultKey(wrapped, recoverySecret, 'acct-7'), vaultKey)
    assert.equal(unwrapVaultKey(wrapped, newSecret(), 'acct-7'), null)
    assert.equal(unwrapVaultKey(wrapped, recoverySecret, 'acct-8'), null)
  })
})
